 on:
   push:
     branches:
       - main
 jobs:
        build-image:
            name: Build container
            runs-on: ubuntu-latest

            steps:
              - name: Login to GitHub Container Registry
                uses: docker/login-action@v2
                with:
                  registry: ghcr.io
                  username: ${{ secrets.GHCR_USERNAME }}
                  password: ${{ secrets.GHCR_TOKEN }}
           
              - name: Build and push
                uses: docker/build-push-action@v3
                with:
                  push: true
                  image: ./Dockerfile
                  tags: ghcr.io/DarshanC1007/x:latest


